### ISSUE TITLE
Terraform 12

### ISSUE THREAD

**Issue by dieend** [bmatcuk/terraform-provider-vagrant#1]
Any plan on upgrading the provider to support terraform 12?

**Comment by bmatcuk** [comment]
Hi @dieend! I'm really, really sorry I didn't see this until just now. I never got any notification that this issue was created; not sure what happened.

It's been a while since I've worked on this, but I'll add terraform 12 support to my list of todos. Might be a while, though =( Sorry.

**Comment by bmatcuk** [comment]
I felt bad for not noticing this for a long time, so I did it! terraform-provider-vagrant v2 adds terraform v0.12 support =) Let me know if you run into problems!
