### ISSUE TITLE
Vagrant SSH login uses wrong SSH key after Terraform apply

### ISSUE THREAD

**Issue by ivanov-slk** [bmatcuk/terraform-provider-vagrant#21]
Hopefully this is the right place to post this :)

I'm running `Terraform v1.1.3 on linux_amd64 + provider registry.terraform.io/bmatcuk/vagrant v4.1.0` and Vagrant 2.2.19; Ubuntu 20.04.

I have provisioned a vagrant box in Virtualbox via Terraform. The VM is configured to run with SSH key pair for login. It initializes correctly in Virtualbox. If I only `vagrant up` the `Vagrantfile` and then `vagrant ssh`  (without using Terraform) I can login successfully.

However, if I run `terraform apply` [details below] the machine starts as usual, but when I try to `vagrant ssh` into the machine it prompts for password (which it should not do).

Running `vagrant ssh -debug` shows some interesting things (excerpt):
```
DEBUG virtualbox_6_1:   - [1, "ssh", 2222, 22, "127.0.0.1"]
DEBUG ssh: Checking key permissions: /home/asdf/.vagrant.d/insecure_private_key
 INFO ssh: Invoking SSH: /usr/bin/ssh ["vagrant@127.0.0.1", "-p", "2222", "-o", "LogLevel=FATAL", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "IdentitiesOnly=yes", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-i", "/home/asdf/.vagrant.d/insecure_private_key"]
vagrant@127.0.0.1's password: 
```
It seems that Vagrant, when invoked by Terraform, looks for the insecure private key (which I do not want to use). If I log in to the machine directly from shell with the correct private key:
```
ssh vagrant@127.0.0.1 -p 2222 -i ~/.ssh/virtual_id_ed25519
```
I log in successfully.

The private key specified in `terraform.tfstate` is the correct one though, although it is formatted with `\n` characters:
```
-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXk>>>>REDACTED<<<<<-----END OPENSSH PRIVATE KEY-----\n
```

This makes me think that something in the interaction between Vagrant and  Terraform goes wrong.

My `Vagrantfile` is as follows:
```
virtual_machine_image_master = ENV["virtual_machine_image_master"]
private_key_path_master = ENV["private_key_path_master"]

Vagrant.configure("2") do |config|
    config.vm.box = virtual_machine_image_master
    config.vm.box_url = "file://./#{virtual_machine_image_master}.box"
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = virtual_machine_image_master

    config.ssh.connect_timeout = 20
    config.ssh.username = "vagrant"
    config.ssh.insert_key = false
    config.ssh.private_key_path = private_key_path_master
    end
  
  end
```

My Terraform `main.tf` is:
```
terraform {
  required_providers {
    vagrant = {
      source  = "bmatcuk/vagrant"
      version = "~> 4.1.0"
    }
  }
}

resource "vagrant_vm" "ubuntu-server-master" {
  vagrantfile_dir = "."
  env = {
    virtual_machine_image_master = var.virtual_machine_image_master,
    private_key_path_master = var.private_key_path_master
  }
  get_ports = true
}
```

My Terraform `variables.tf` are:
```
variable "virtual_machine_image_master" {
    type = string
    default = "ubuntu-20.04.3-live-server-amd64-master"
}

variable "private_key_path_master" {
  type    = string
  default = "/home/asdf/.ssh/virtual_id_ed25519"
}
```

**Comment by bmatcuk** [comment]
hmm, because the vagrant file specifies the path to the ssh key using an environment variable, shouldn't you need to do something like:

```bash
env private_key_path_master=/home/asdf/.ssh/virtual_id_ed25519 vagrant ssh
```

to connect?

I'm guessing it works if you bring it up manually (ie, `vagrant up` + `vagrant ssh`) because you aren't specifying your environment variable in both cases, so it's defaulting to the insecure key both times. When you use terraform, it's bringing the machine up with the environment variable set, but `vagrant ssh` by itself won't work because the environment variable is unset.

**Comment by ivanov-slk** [comment]
Riiight... this makes sense.

I tried it and it works: setting `private_key_path_master` as environment variable in the shell from which I'm running `vagrant ssh` logs me into the VM successfully; too bad I have to either hardcode the private key in the Vagrantfile or explicitly set it as environment variable in the shell I want to `vagrant ssh` from. Is there any way to fetch it from Terraform?

E.g. I have already `variables.tf` which is coded in HCL - can I pass somehow this configuration to the Vagrantfile?

**Comment by bmatcuk** [comment]
Well, a Vagrantfile is just ruby... you could write some code to parse the path out of your variables.tf. Perhaps a better thing to do would be to use something like [dotenv](https://github.com/bkeepers/dotenv) in your Vagrantfile to load the path out of a file, and then you could remove it from your terraform config (since the Vagrantfile would be reading it from this other file). You really don't even need a fancy gem to read a path out of a file if you want to keep it really simple with no dependencies.

**Comment by ivanov-slk** [comment]
Thanks. I'll look into this.

As far as the issue... it seems that there is no (easy) way to get around this and it could be probably closed...

**Comment by bmatcuk** [comment]
Ok, good luck!
