### ISSUE TITLE
Question: How to provision only

### ISSUE THREAD

**Issue by Jeansen** [bmatcuk/terraform-provider-vagrant#38]
I wonder, how I would do the following use case with this provider where I would first run `vagrant up --no-provision` and afterwards `vagrant provision`?

**Comment by bmatcuk** [comment]
Hmm, that use case is not supported and I'm not sure how I could make it work within terraform, since it doesn't have a similar concept. Perhaps you could do some trickery using environment variables?

**Comment by Jeansen** [comment]
Thanks for the quick reply @bmatcuk. It's ok, when it is not supported. I have all I need in a script, but am moving to terraform. I would give some ideas, but I am all too new to terraform.  Anyway, maybe it would not be that a bad idea to have some more options at hand aside from up and destroy ;-)

In my case, maybe I can work with some experimental features using dependency provisioners or simply use terraform provisioners and rework my Vagrantfile. Should I close this one, then?

**Comment by bmatcuk** [comment]
Sorry for my slower reply this time, lol. Ya, I don't see any way to support this in terraform - it's a limitation in the way terraform works compared to vagrant. I'll close this issue.
