### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by fairbairn** [bmatcuk/terraform-provider-vagrant#4]
Been chasing this for hours...

Using Terraform 14.
I can't seem to get a setup where the binary can be detected vs terraform thinking it wants to load "hashicorp/vagrant" from the registry in the cloud.
I've placed in `.terraform.d/plugins/darwin_amd64`, no difference.
I'm at a loss as to how to get the terraform init to pass, it just can't seem to figure out what to do
It would be grand if it could just load over the wire with a source= reference, build it, and go, but I realize that does not work (I tried).

Can we enhance the documentation to be a bit more current and explicit, now that we're in Terraform 14 land?

If anyone else has a working combination, I'd love to see the example.

**Comment by fairbairn** [comment]
For those in limbo, here is how you do it...

in your main.tf, you need this..

```
terraform {
  required_version = ">= 0.14"
  backend "local" {}
  required_providers {
    vagrant = {
      source  = "github.com/bmatcuk/vagrant"
      version = "2.0.0"
    }
  }
}
```
in your $HOME folder, you need this..

```
$ tree ~/.terraform.d/plugins                                                                                                      
$HOME/.terraform.d/plugins
└── github.com
    └── bmatcuk
        └── vagrant
            └── 2.0.0
                └── darwin_amd64
                    └── terraform-provider-vagrant_v2.0.0
``` 

Keep in mind that the target platform would change.  Mine is a mac, so darwin_amd64.

Hope this helps someone save lots of hours of headache.

**Comment by bmatcuk** [comment]
Sorry for the trouble you had... when I wrote this provider, the registry wasn't a thing and using third-party providers was as simple as copying the executable to the right place.

I've now published terraform-provider-vagrant to the registry as bmatcuk/vagrant. Should be much easier to use now =)
