### ISSUE TITLE
Add forwarded ports to Terraform attributes

### ISSUE THREAD

**Issue by palfrey** [bmatcuk/terraform-provider-vagrant#5]
It would be useful to get this data in the Terraform attributes, especially as `go-vagrant` supports getting this data already.

Thanks for the provider, it's been very useful!

**Comment by bmatcuk** [comment]
Hey @palfrey! Sorry this took me forever to get to 😢 I finally added support for forwarded ports. Additionally, the provider is [available in the registery](https://registry.terraform.io/providers/bmatcuk/vagrant/latest) now, so it'll be a lot easier to install.

You'll need to set `get_ports` to true in the `resource` block. The ports are provided in `ports`.

**Comment by palfrey** [comment]
Awesome. I've switched over from https://registry.terraform.io/providers/lippertmarkus/vagrant/ 's registry instance to yours, and ports are all turning up. Thanks!

**Comment by bmatcuk** [comment]
Awesome!
